# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import simulation_pb2 as simulation__pb2


class SimulatorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateSimulation = channel.unary_unary(
                '/Simulator/CreateSimulation',
                request_serializer=simulation__pb2.CreateSimulationRequest.SerializeToString,
                response_deserializer=simulation__pb2.Simulation.FromString,
                )
        self.Simulate = channel.unary_unary(
                '/Simulator/Simulate',
                request_serializer=simulation__pb2.SimulationAction.SerializeToString,
                response_deserializer=simulation__pb2.Simulation.FromString,
                )
        self.GetFeaturesV2 = channel.unary_unary(
                '/Simulator/GetFeaturesV2',
                request_serializer=simulation__pb2.Simulation.SerializeToString,
                response_deserializer=simulation__pb2.FeaturesV2.FromString,
                )


class SimulatorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateSimulation(self, request, context):
        """CreateSimulation - returns a new Simulation State
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Simulate(self, request, context):
        """Simulate - Request an action on a Simulation
        Returns the new Simulation State
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFeaturesV2(self, request, context):
        """GetFeaturesV2 - Given a simulation return v2 features
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SimulatorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateSimulation': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateSimulation,
                    request_deserializer=simulation__pb2.CreateSimulationRequest.FromString,
                    response_serializer=simulation__pb2.Simulation.SerializeToString,
            ),
            'Simulate': grpc.unary_unary_rpc_method_handler(
                    servicer.Simulate,
                    request_deserializer=simulation__pb2.SimulationAction.FromString,
                    response_serializer=simulation__pb2.Simulation.SerializeToString,
            ),
            'GetFeaturesV2': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFeaturesV2,
                    request_deserializer=simulation__pb2.Simulation.FromString,
                    response_serializer=simulation__pb2.FeaturesV2.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Simulator', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Simulator(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateSimulation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Simulator/CreateSimulation',
            simulation__pb2.CreateSimulationRequest.SerializeToString,
            simulation__pb2.Simulation.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Simulate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Simulator/Simulate',
            simulation__pb2.SimulationAction.SerializeToString,
            simulation__pb2.Simulation.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetFeaturesV2(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Simulator/GetFeaturesV2',
            simulation__pb2.Simulation.SerializeToString,
            simulation__pb2.FeaturesV2.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
